Repository projectsyn/lieutenant-api, pull requests merged in 2021-06, with the labels that each got.

#146 Provide installURL when returning Cluster objects
  pkg/service/cluster.go
  pkg/service/cluster_test.go
Labels: enhancement

#148 Update dependencies
  go.mod
  go.sum
  pkg/api/client.go
  pkg/api/openapi.go
  pkg/service/api_service_test.go
Labels: dependency

#147 Disable goModTidy for Renovate
  renovate.json
Labels: change

#151 New style for documentation preview
  Makefile
  docs/modules/ROOT/assets/images/projectsyn.svg
  docs/modules/ROOT/pages/index.adoc
Labels: documentation, enhancement
